name: CI Pipeline Basique  # Nom du workflow

on:  # Événements qui déclenchent le workflow
  push:  # Sur chaque push
    branches: [ main ]  # Sur la branche main
  pull_request:  # Sur les pull requests
    branches: [ main ]

jobs:  # Les tâches à exécuter
  build:  # Nom du job
    runs-on: ubuntu-latest  # Machine virtuelle : Ubuntu dernière version

    steps:  # Étapes du job
      - uses: actions/checkout@v3  # Étape 1 : Cloner le dépôt

      - name: Installer Python  # Étape 2 : Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Version de Python

      - name: Mettre à jour pip et installer pytest  # Étape 3 : Mettre à jour pip et installer pytest directement
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Pas de requirements.txt ici

      - name: Exécuter les tests  # Étape 4 : Lancer les tests avec pytest
        run: pytest